network: "beeline_networks/Curated_GSD.csv"
ns: 19

tfinal: 10.0
ntotal: 10
nplot: 100
batch_size: 10
epoch_size: -1

lr: 1.e-3
weight_decay: 1.e-5
grad_max: 1.e-0

n_mu: 5

n_exp_train: 20
n_exp_val: 5
n_exp_test: 5
noise: 0.01

n_iter_max: 10000
n_plot: 20 # frequency of callback

n_iter_buffer: -1
n_iter_burnin: 10
n_iter_tol: 50
convergence_tol: 1e-30
