is_restart: false
ns: 5

tfinal: 20.0
ntotal: 20
batch_size: 8
epoch_size: -1

lr: 1.e-3
weight_decay: 1.e-4

n_mu: 3

n_exp_train: 20
n_exp_val: 10
n_exp_test: 10
noise: 0.01

n_iter_max: 1000
n_plot: 20 # frequency of callback

n_iter_buffer: 50
n_iter_burnin: 100
n_iter_tol: 10
convergence_tol: 1e-8

sparsity: 0.6
drop_range:
   lb: -0.1
   ub: 0.1
