network: "beeline_networks/Synthetic_BF.csv"
ns: 7
alpha: 1.0

tfinal: 20.0
ntotal: 5
nplot: 100
batch_size: 5
epoch_size: 10

lr: 5.e-4
weight_decay: 1.e-8

n_mu: 2

n_exp_train: 50
n_exp_val: 5
n_exp_test: 5
noise: 0.01

n_iter_max: 10000
n_plot: 20 # frequency of callback

n_iter_buffer: 50
n_iter_burnin: 100
n_iter_tol: 100
convergence_tol: 1e-8
