data: "data/skmel133_24"
ns: 24
alpha: 1.0
tfinal: 20.0
ntotal: 1
nplot: 100
batch_size: 1
epoch_size: -1

lr: 1.e-4
weight_decay: 1.e-6

n_mu: 2

n_exp_train: 69
n_exp_val: 10
n_exp_test: 10
noise: 0.01

n_iter_max: 10000
n_plot: 20 # frequency of callback

n_iter_buffer: 50
n_iter_burnin: 100
n_iter_tol: 100
convergence_tol: 1e-8
