network: "beeline_networks/Curated_VSC.csv"
ns: 8

tfinal: 20.0
ntotal: 5
nplot: 100
batch_size: 1
epoch_size: -1

lr: 1.e-3
weight_decay: 1.e-10

n_mu: 2

n_exp_train: 50
n_exp_val: 10
n_exp_test: 10
noise: 0.001

n_iter_max: 10000
n_plot: 20 # frequency of callback

n_iter_buffer: 50
n_iter_burnin: 100
n_iter_tol: 100
convergence_tol: 1e-8
