network: "beeline_networks/Synthetic_BFC.csv"
ns: 10

tfinal: 20.0
ntotal: 10
nplot: 100
batch_size: 5
epoch_size: -1

lr: 1.e-3
weight_decay: 1.e-12

n_mu: 2

n_exp_train: 30
n_exp_val: 5
n_exp_test: 5
noise: 0.01

n_iter_max: 10000
n_plot: 20 # frequency of callback

n_iter_buffer: 50
n_iter_burnin: 100
n_iter_tol: 5000
convergence_tol: 1e-8
